driver:
  name: proxy
  reset_command: cli -c 'configure; rollback rescue; commit'

provisioner:
  name: chef_solo
  root_path: /var/tmp/kitchen
  # The Chef for Junos package does not exist on Omnitruck yet.
  require_chef_omnibus: false
  # `sudo` does not exist on the switches
  sudo: false

busser:
  # `sudo` does not exist on the switches
  sudo: false
  root_path: /var/tmp/busser
  # Chef is installed into a non-Omnibus (/opt/chef) path
  ruby_bindir: /opt/sdk/chef/bin
  busser_bin: /opt/sdk/chef/bin/ruby /var/tmp/busser/gems/bin/busser

platforms:
- name: junos-13.2

suites:
- name: interface
  run_list: interface::create
- name: l2_interface
  run_list: l2_interface::create
- name: lag
  run_list: lag::create
- name: vlan
  run_list: vlan::create
